#-- Lattice Semiconductor Corporation Ltd.
#-- Place & Route run script generated by Radiant

set ret 0
if {[catch {

if {![file exists {/build/impl}]} {
  file mkdir {/build/impl}
}
cd {/build/impl}

sys_set_attribute -gui on -msg {/build/promote.xml}
msg_load {/build/promote.xml}
des_set_project_udb -in {top_impl_map.udb} -out {top_impl.udb} -milestone par -pm je5d00
des_set_reference_udb -clean
# par option
par_set_option { disable_timing_driven false placement_iterations 1 placement_iteration_start_point 1 placement_save_best_run "1"  number_of_host_machine_cores "1" path_based_placement off  stop_once_timing_is_met false   set_speed_grade_for_hold_optimization m disable_auto_hold_timing_correction false prioritize_hold_correction_over_setup_performance false run_placement_only false impose_hold_timing_correction false}
# run place & route
par_run
# backup netlist & constraint file
if {[file exists {/build/impl/top_impl_syn.udb}] && [file exists {/build/impl/top_impl_map.udb}] && [file exists {/build/impl/top_impl.udb}]} {
  file delete -force {/build/impl/incr/top_impl_syn.udb} {/build/impl/incr/top_impl_map.udb} {/build/impl/incr/top_impl.udb} {/build/impl/incr/lastrun.pdc}
  file copy -force -- {/build/impl/top_impl_syn.udb} {/build/impl/incr/postsyn.udb}
  file copy -force -- {/build/impl/top_impl_map.udb} {/build/impl/incr/postmap.udb}
  file copy -force -- {/build/impl/top_impl.udb} {/build/impl/incr/postpar.udb}
  if [file exists {/build/top.pdc}] {
    file copy -force -- {/build/top.pdc} {/build/impl/incr/lastrun.pdc}
  }
}

} out]} {
   puts $out
   set ret 1
}

exit -force ${ret}
