#-- Lattice Semiconductor Corporation Ltd.
#-- Bitgen run script generated by Radiant

set ret 0
if {[catch {

sys_set_attribute -gui on -msg {/build/promote.xml}
msg_load {/build/promote.xml}
des_set_project_udb -in {top_impl.udb} -milestone bit -pm je5d00
# bitgen option
bit_set_option { enable_early_io_wakeup false output_format "binary"   ip_evaluation false register_initialization true bitstream_mode normal }
#-- write result file
bit_generate -w {/build/impl/top_impl}

} out]} {
   puts $out
   set ret 1
}

exit -force ${ret}
