#-- Lattice Semiconductor Corporation Ltd.
#-- Map run script generated by Radiant

set ret 0
if {[catch {

if {![file exists {/build/impl}]} {
  file mkdir {/build/impl}
}
cd {/build/impl}

sys_set_attribute -gui on -msg {/build/promote.xml}
msg_load {/build/promote.xml}
des_set_project_udb -in {top_impl_syn.udb} -out {top_impl_map.udb} -milestone map -pm je5d00
des_set_reference_udb -clean
map_set_option {pdc_file "/build/top.pdc"}
# map option
map_set_option { report_symbol_cross_reference false report_signal_cross_reference false infer_gsr false  ignore_constraint_errors false vio false}
map_run

} out]} {
   puts $out
   set ret 1
}
exit -force ${ret}
