@rem Automatically generated by Amaranth 0.5.4. Do not edit.
@echo off
SetLocal EnableDelayedExpansion
if defined AMARANTH_ENV_RADIANT call "%AMARANTH_ENV_RADIANT%"
if [!RADIANTC!] equ [""] set RADIANTC=
if [!RADIANTC!] equ [] set RADIANTC=radiantc
"%RADIANTC%" top.tcl || exit /b
