[package]
name = "litex-pac"
version = "0.1.0"
edition = "2021"

[dependencies]
critical-section = { version = "1.0", optional = true }
riscv = "0.9.0"
riscv-rt = { version = "0.9.0", optional = true }
vcell = "0.1.0"

[features]
rt = ["riscv-rt"]