/*
 * Automatically generated by LUNA; edits will be discarded on rebuild.
 * (Most header files phrase this 'Do not edit.'; be warned accordingly.)
 *
 * Generated: 2026-01-14 20:01:03.292269.
 */

MEMORY {
    blockram : ORIGIN = 0x00000000, LENGTH = 0x00040000
    spiflash : ORIGIN = 0x10000000, LENGTH = 0x00400000
}

REGION_ALIAS("REGION_TEXT", blockram);
REGION_ALIAS("REGION_RODATA", blockram);
REGION_ALIAS("REGION_DATA", blockram);
REGION_ALIAS("REGION_BSS", blockram);
REGION_ALIAS("REGION_HEAP", blockram);
REGION_ALIAS("REGION_STACK", blockram);
